# src/main/resources/application.properties

# The port Spring Boot listens on. React will call http://localhost:8080/api
server.port=8080

# Allow server (port 3000 or 5173) to call this backend.
cors.allowed-origins=http://localhost:3000,http://localhost:5173